Repository serilog-contrib/serilog-sinks-splunk, pull requests merged in 2024-04, with the labels that each got.

#174 Set up GitHub Actions
  .github/release.yml
  .github/workflows/ci-release.yml
  .github/workflows/ci.yml
  .gitignore
  Build.ps1
  Setup.ps1
  appveyor.yml
  build.sh
  docker-compose.dcproj
  global.json
  sample/Sample/Sample.csproj
  serilog-sinks-splunk.sln
  src/Serilog.Sinks.Splunk/Serilog.Sinks.Splunk.csproj
  src/Serilog.Sinks.TCP/Serilog.Sinks.Splunk.TCP.csproj
  src/Serilog.Sinks.UDP/Serilog.Sinks.Splunk.UDP.csproj
  test/Serilog.Sinks.Splunk.Tests/Serilog.Sinks.Splunk.Tests.csproj
Labels: enhancement

#176 Security Policy, scanning and dependency updates
  .github/dependabot.yml
  .github/workflows/codeql.yml
  SECURITY.md
Labels: dependencies

#181 Updates for UDP and TCP sinks for periodic batching changes
  src/Serilog.Sinks.Splunk/Sinks/Splunk/EventCollectorSink.cs
  src/Serilog.Sinks.Splunk/Sinks/Splunk/SplunkJsonFormatter.cs
  src/Serilog.Sinks.Splunk/SplunkLoggingConfigurationExtensions.cs
  src/Serilog.Sinks.TCP/Sinks/Splunk/TcpSink.cs
  src/Serilog.Sinks.TCP/SplunkLoggingConfigurationExtensions.cs
  src/Serilog.Sinks.UDP/Sinks/Splunk/UdpSink.cs
  src/Serilog.Sinks.UDP/SplunkLoggingConfigurationExtensions.cs
Labels: enhancement, Semver-Patch

#186 Create a common.props for version number and nuget package info.
  Build.ps1
  sample/Sample/Program.cs
  serilog-sinks-splunk.sln
  src/Serilog.Sinks.Splunk/Serilog.Sinks.Splunk.csproj
  src/Serilog.Sinks.TCP/Serilog.Sinks.Splunk.TCP.csproj
  src/Serilog.Sinks.UDP/Serilog.Sinks.Splunk.UDP.csproj
  src/common.props
Labels: ignore-for-release

#196 Attempt reproduction of #195
  DockerfileSolutionRestore.txt
  sample/Sample/Dockerfile
  sample/Sample/Program.cs
  sample/Sample/Sample.csproj
  src/Serilog.Sinks.Splunk/Sinks/Splunk/SplunkJsonFormatter.cs
Labels: enhancement, Semver-Patch
